import Splash from './splash';
import GetStarted from './GetStarted';
import Register from './Register';
import SignIn from './SignIn';
import UploadPhoto from './UploadPhoto';
import Hospital from './Hospital';
import Doctor from './Doctor';
import Messages from './Messages';
import ChooseDoctor from './ChooseDoctor';
import Chatting from './Chatting';
export {Splash,GetStarted,Register,SignIn,UploadPhoto,Hospital,Doctor,Messages,ChooseDoctor,Chatting};
